//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOL.Revit.SampleAddin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UOL.Revit.SampleAddin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add_64x64 {
            get {
                object obj = ResourceManager.GetObject("Add_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Object Library for Revit.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Buttons_Cancel {
            get {
                return ResourceManager.GetString("Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Buttons_Close {
            get {
                return ResourceManager.GetString("Buttons_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Buttons_OK {
            get {
                return ResourceManager.GetString("Buttons_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid email address.
        /// </summary>
        public static string CaptionEmailExpected {
            get {
                return ResourceManager.GetString("CaptionEmailExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit_64x64 {
            get {
                object obj = ResourceManager.GetObject("Edit_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon2 {
            get {
                object obj = ResourceManager.GetObject("icon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon4 {
            get {
                object obj = ResourceManager.GetObject("icon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconV1 {
            get {
                object obj = ResourceManager.GetObject("iconV1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconV164 {
            get {
                object obj = ResourceManager.GetObject("iconV164", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconV2 {
            get {
                object obj = ResourceManager.GetObject("iconV2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconV264 {
            get {
                object obj = ResourceManager.GetObject("iconV264", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconV3 {
            get {
                object obj = ResourceManager.GetObject("iconV3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap iconV364 {
            get {
                object obj = ResourceManager.GetObject("iconV364", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Logo_UOB {
            get {
                object obj = ResourceManager.GetObject("Logo_UOB", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation request failed!.
        /// </summary>
        public static string MessageBoxAddValidationRequestError_Text {
            get {
                return ResourceManager.GetString("MessageBoxAddValidationRequestError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred trying to download the CAD content for the selection. Please try again later..
        /// </summary>
        public static string MessageBoxCadacContentDownloadError_Text {
            get {
                return ResourceManager.GetString("MessageBoxCadacContentDownloadError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CAD object can’t be created because the selected UOL object has missing or incorrect data..
        /// </summary>
        public static string MessageBoxCadContentIncomplete_Text {
            get {
                return ResourceManager.GetString("MessageBoxCadContentIncomplete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected CAD file was loaded in the Revit project, but it can&apos;t be placed in the current view..
        /// </summary>
        public static string MessageBoxCadContentLoadedCantPlace_Text {
            get {
                return ResourceManager.GetString("MessageBoxCadContentLoadedCantPlace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compatible CAD file for the selection is currently not available..
        /// </summary>
        public static string MessageBoxCadContentNotFound_Text {
            get {
                return ResourceManager.GetString("MessageBoxCadContentNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CAD object can’t be created because the selected UOL object has missing required property values..
        /// </summary>
        public static string MessageBoxCadPropertiesIncomplete_Text {
            get {
                return ResourceManager.GetString("MessageBoxCadPropertiesIncomplete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EtimClass and/or ModellingClass have changed, this is not allowed!.
        /// </summary>
        public static string MessageBoxECcodeMCcodeChangeNotAllowed_Text {
            get {
                return ResourceManager.GetString("MessageBoxECcodeMCcodeChangeNotAllowed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid email address is expected! Fill in a valid email address to proceed..
        /// </summary>
        public static string MessageBoxEmailExpected {
            get {
                return ResourceManager.GetString("MessageBoxEmailExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while getting the validations for the active project..
        /// </summary>
        public static string MessageBoxGetValidationsError_Text {
            get {
                return ResourceManager.GetString("MessageBoxGetValidationsError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection contains multiple family types. Only one family type is supported!
        ///Only select instances of the same family type..
        /// </summary>
        public static string MessageBoxMultipleTypesInSelectionNotAllowed_Text {
            get {
                return ResourceManager.GetString("MessageBoxMultipleTypesInSelectionNotAllowed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no content searched, first search for content, after that you can edit..
        /// </summary>
        public static string MessageBoxNoContentSearched_Text {
            get {
                return ResourceManager.GetString("MessageBoxNoContentSearched_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Project Id to get validations for, check the Project Information part of your model. The ProjectNumber field has to contains the Project Id..
        /// </summary>
        public static string MessageBoxProcessValidationNoProjectId_Text {
            get {
                return ResourceManager.GetString("MessageBoxProcessValidationNoProjectId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected element isn&apos;t UOL or it doesn&apos;t contain the correct UOL data to edit it..
        /// </summary>
        public static string MessageBoxSelectedElementIsNotUOLContent_Text {
            get {
                return ResourceManager.GetString("MessageBoxSelectedElementIsNotUOLContent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete ticket {0}?.
        /// </summary>
        public static string MessageBoxValidationDelete_Text {
            get {
                return ResourceManager.GetString("MessageBoxValidationDelete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket {0} has been deleted..
        /// </summary>
        public static string MessageBoxValidationDeleted_Text {
            get {
                return ResourceManager.GetString("MessageBoxValidationDeleted_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion of ticket {0} aborted. Nothing is deleted..
        /// </summary>
        public static string MessageBoxValidationNotDeleted_Text {
            get {
                return ResourceManager.GetString("MessageBoxValidationNotDeleted_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation results of ticket {0} have been added to {1} CAD object(s)..
        /// </summary>
        public static string MessageBoxValidationProcessed_Text {
            get {
                return ResourceManager.GetString("MessageBoxValidationProcessed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing errors: {0}.
        /// </summary>
        public static string MessageBoxValidationProcessedErrors_Text {
            get {
                return ResourceManager.GetString("MessageBoxValidationProcessedErrors_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation report for ticket {0} is not available at the moment!.
        /// </summary>
        public static string MessageBoxValidationReportNotAvailable_Text {
            get {
                return ResourceManager.GetString("MessageBoxValidationReportNotAvailable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation request cannot be loaded!.
        /// </summary>
        public static string MessageBoxValidationRequestNotFound_Text {
            get {
                return ResourceManager.GetString("MessageBoxValidationRequestNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of ticket {0} is restarted..
        /// </summary>
        public static string MessageBoxValidationRestart_Text {
            get {
                return ResourceManager.GetString("MessageBoxValidationRestart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no validation result available to process!.
        /// </summary>
        public static string MessageBoxValidationResultNotAvailable_Text {
            get {
                return ResourceManager.GetString("MessageBoxValidationResultNotAvailable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the family instances to validate..
        /// </summary>
        public static string MessageSelectFamilyInstancesToValidate {
            get {
                return ResourceManager.GetString("MessageSelectFamilyInstancesToValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In CAD processed validations are deleted immediately from the UOL platform.
        ///Validations are only 30 days available..
        /// </summary>
        public static string ProcessValidation_Explanation {
            get {
                return ResourceManager.GetString("ProcessValidation_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element with Id: {0} could not be processed. Error: {1}..
        /// </summary>
        public static string ProcessValidation_ProcessErrorElement {
            get {
                return ResourceManager.GetString("ProcessValidation_ProcessErrorElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Validation results....
        /// </summary>
        public static string ProcessValidation_Processing {
            get {
                return ResourceManager.GetString("ProcessValidation_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list of Validation requests.
        /// </summary>
        public static string ProcessValidation_RefreshList {
            get {
                return ResourceManager.GetString("ProcessValidation_RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ProcessValidation_RequestDate {
            get {
                return ResourceManager.GetString("ProcessValidation_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ProcessValidation_RequestStatus {
            get {
                return ResourceManager.GetString("ProcessValidation_RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number.
        /// </summary>
        public static string ProcessValidation_TicketNumber {
            get {
                return ResourceManager.GetString("ProcessValidation_TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate &gt; process validation.
        /// </summary>
        public static string ProcessValidation_Title {
            get {
                return ResourceManager.GetString("ProcessValidation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete validation request.
        /// </summary>
        public static string ProcessValidation_TooltipDelete {
            get {
                return ResourceManager.GetString("ProcessValidation_TooltipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process validation result.
        /// </summary>
        public static string ProcessValidation_TooltipProcess {
            get {
                return ResourceManager.GetString("ProcessValidation_TooltipProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh validation result list.
        /// </summary>
        public static string ProcessValidation_TooltipRefresh {
            get {
                return ResourceManager.GetString("ProcessValidation_TooltipRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open report with validation result.
        /// </summary>
        public static string ProcessValidation_TooltipReport {
            get {
                return ResourceManager.GetString("ProcessValidation_TooltipReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart validation request.
        /// </summary>
        public static string ProcessValidation_TooltipRestart {
            get {
                return ResourceManager.GetString("ProcessValidation_TooltipRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % valid.
        /// </summary>
        public static string ProcessValidation_ValidationResult {
            get {
                return ResourceManager.GetString("ProcessValidation_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validations.
        /// </summary>
        public static string ProcessValidation_Validations {
            get {
                return ResourceManager.GetString("ProcessValidation_Validations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Registry_Key_Language {
            get {
                return ResourceManager.GetString("Registry_Key_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Registry_SubKey_User {
            get {
                return ResourceManager.GetString("Registry_SubKey_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active view.
        /// </summary>
        public static string RequestValidation_ActiveView {
            get {
                return ResourceManager.GetString("RequestValidation_ActiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        public static string RequestValidation_ButtonSelection {
            get {
                return ResourceManager.GetString("RequestValidation_ButtonSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RequestValidation_Description {
            get {
                return ResourceManager.GetString("RequestValidation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string RequestValidation_EmailAddress {
            get {
                return ResourceManager.GetString("RequestValidation_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of UOL instances.
        /// </summary>
        public static string RequestValidation_NumberOfInstances {
            get {
                return ResourceManager.GetString("RequestValidation_NumberOfInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting data for validation....
        /// </summary>
        public static string RequestValidation_Progress {
            get {
                return ResourceManager.GetString("RequestValidation_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation request completed. 
        ///Choose in the ribbon Validate -&gt; Process validation to get a list of all validation requests with status..
        /// </summary>
        public static string RequestValidation_ProgressFinish {
            get {
                return ResourceManager.GetString("RequestValidation_ProgressFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string RequestValidation_Project {
            get {
                return ResourceManager.GetString("RequestValidation_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string RequestValidation_Properties {
            get {
                return ResourceManager.GetString("RequestValidation_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string RequestValidation_RequestDate {
            get {
                return ResourceManager.GetString("RequestValidation_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only differences.
        /// </summary>
        public static string RequestValidation_ResultDifferences {
            get {
                return ResourceManager.GetString("RequestValidation_ResultDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string RequestValidation_ResultFull {
            get {
                return ResourceManager.GetString("RequestValidation_ResultFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result in CAD.
        /// </summary>
        public static string RequestValidation_ResultInCAD {
            get {
                return ResourceManager.GetString("RequestValidation_ResultInCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string RequestValidation_Selection {
            get {
                return ResourceManager.GetString("RequestValidation_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection options.
        /// </summary>
        public static string RequestValidation_SelectionOptions {
            get {
                return ResourceManager.GetString("RequestValidation_SelectionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number.
        /// </summary>
        public static string RequestValidation_TicketNumber {
            get {
                return ResourceManager.GetString("RequestValidation_TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate &gt; Request validation.
        /// </summary>
        public static string RequestValidation_Title {
            get {
                return ResourceManager.GetString("RequestValidation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string RibbonButton_ValidateDescription {
            get {
                return ResourceManager.GetString("RibbonButton_ValidateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides options to add validation requests and to show validation results for the active project..
        /// </summary>
        public static string RibbonButton_ValidateLongDescription {
            get {
                return ResourceManager.GetString("RibbonButton_ValidateLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string RibbonButton_ValidateSubProcessValidationDescription {
            get {
                return ResourceManager.GetString("RibbonButton_ValidateSubProcessValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process validation results into CAD..
        /// </summary>
        public static string RibbonButton_ValidateSubProcessValidationTooltip {
            get {
                return ResourceManager.GetString("RibbonButton_ValidateSubProcessValidationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string RibbonButton_ValidateSubRequestValidationDescription {
            get {
                return ResourceManager.GetString("RibbonButton_ValidateSubRequestValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new validation request..
        /// </summary>
        public static string RibbonButton_ValidateSubRequestValidationTooltip {
            get {
                return ResourceManager.GetString("RibbonButton_ValidateSubRequestValidationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add validation requests or show validation results..
        /// </summary>
        public static string RibbonButton_ValidateTooltip {
            get {
                return ResourceManager.GetString("RibbonButton_ValidateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string RibbonButtonEditInstancesDescription {
            get {
                return ResourceManager.GetString("RibbonButtonEditInstancesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides access to the Uniform Object Library and show only corresponding CAD objects according to the selection.
        ///Replace the selection with updated CAD objects..
        /// </summary>
        public static string RibbonButtonEditInstancesLongDescription {
            get {
                return ResourceManager.GetString("RibbonButtonEditInstancesLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update selection using the Uniform Object Library..
        /// </summary>
        public static string RibbonButtonEditInstancesTooltip {
            get {
                return ResourceManager.GetString("RibbonButtonEditInstancesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string RibbonButtonSearchDescription {
            get {
                return ResourceManager.GetString("RibbonButtonSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides access to the Uniform Object Libary to filter and search for CAD objects..
        /// </summary>
        public static string RibbonButtonSearchLongDescription {
            get {
                return ResourceManager.GetString("RibbonButtonSearchLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for CAD objects within the Uniform Object Library..
        /// </summary>
        public static string RibbonButtonSearchTooltip {
            get {
                return ResourceManager.GetString("RibbonButtonSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Objects Sample.
        /// </summary>
        public static string RibbonName {
            get {
                return ResourceManager.GetString("RibbonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string RibbonPanel_Validate {
            get {
                return ResourceManager.GetString("RibbonPanel_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Objects.
        /// </summary>
        public static string RibbonSearchPanel {
            get {
                return ResourceManager.GetString("RibbonSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not validated.
        /// </summary>
        public static string ValidationProductStatus_0 {
            get {
                return ResourceManager.GetString("ValidationProductStatus_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different structure, product not checked.
        /// </summary>
        public static string ValidationProductStatus_1 {
            get {
                return ResourceManager.GetString("ValidationProductStatus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid structure.
        /// </summary>
        public static string ValidationProductStatus_10 {
            get {
                return ResourceManager.GetString("ValidationProductStatus_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid data.
        /// </summary>
        public static string ValidationProductStatus_11 {
            get {
                return ResourceManager.GetString("ValidationProductStatus_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different data.
        /// </summary>
        public static string ValidationProductStatus_2 {
            get {
                return ResourceManager.GetString("ValidationProductStatus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        public static string ValidationStatus_0 {
            get {
                return ResourceManager.GetString("ValidationStatus_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string ValidationStatus_1 {
            get {
                return ResourceManager.GetString("ValidationStatus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string ValidationStatus_2 {
            get {
                return ResourceManager.GetString("ValidationStatus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string ValidationStatus_3 {
            get {
                return ResourceManager.GetString("ValidationStatus_3", resourceCulture);
            }
        }
    }
}
